### ISSUE TITLE
Curiosity : What other mods do you have on your Bowden Tubes?

### ISSUE THREAD

**Issue by LostFool** [geoffrey-young/filament-buffer#11]
I see some unique items for your bowden connections to the ERCF. Can you share?
Also love this buffer system. i think you should incorporate issue #10, the recessed magnet buffer tops. 
I'm also considering spinning up the CAD for you. I am a mechanical designer and would love to give back somehow. I just can't promise time frames, busy daddy life, shop life, 40hours too much work life.

Referencing this picture : https://github.com/geoffrey-young/pika-filament-buffer/blob/main/images/artie-square.jpg

**Comment by geoffrey-young** [comment]
everything I use on my ercf can be found here: https://github.com/geoffrey-young/3D-Printing/tree/main/models/voron/ercf

thanks for the offer of cad help.  it's probably a wasted effort, as I'd need to verify each part in blender since that's my workflow engine, and any changes I wouldn't really be able to port back.

happy to chat over on discord :)

**Comment by LostFool** [comment]
Thank you, appreciate the reply. sorry for my slow response, hardly enough time for anything in the day.
