### ISSUE TITLE
3 slot version?

### ISSUE THREAD

**Issue by Krakert** [geoffrey-young/filament-buffer#8]
I would like to see a 3 slot version please, I want to mount 3 spools at each side of my printer, with a buffer. So A 3 slot version would be really helpful!

**Comment by ronpandolfi** [comment]
I am actively building a 2x3 myself now. I remodeled some parts here: https://www.printables.com/model/610307-pika-filament-buffer-3x-parts

**Comment by Krakert** [comment]
@ronpandolfi great work, maybe a idea to open a pull requests to add the files to the repo?

**Comment by ronpandolfi** [comment]
> @ronpandolfi great work, maybe a idea to open a pull requests to add the files to the repo?

Will do. 

I'm also currently testing a special mounting bracket for putting a 3x module on each side of an ERCF. It fits well on a V2 300, with space for a spool rack at the rear. I think this fits more as a "mod" though, since the layout is fairly specific.

Edit: https://github.com/geoffrey-young/pika-filament-buffer/pull/9

**Comment by geoffrey-young** [comment]
I added 3 cart files to the dev branch. Please let me know if they work ok, then I'll merge to main.

**Comment by geoffrey-young** [comment]
closing
